import type {SourceAssetPackage} from '../contracts/workflow-draft.js';
import type {AssistedIngestReceipt} from '../ingest/assisted.js';
const escape = (s: unknown): string => String(s).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[c]!);
const anchor = (id: string) => `e-${encodeURIComponent(id)}`;
const localUri = (uri: string) => { if (!/^assets\/\d+\.(mp4|mov|txt|srt)$/.test(uri)) throw new Error('Unsafe report media URI'); return uri; };
const status = {observed:'观察记录（人工提供，未语义核验）',inferred:'推断 · 待确认',reconstructed:'近似重建 · 待确认'};

/** Source-only review: every assertion remains attached to its evidence and uncertainty. */
export function renderSourceReport(p: SourceAssetPackage, receipt: AssistedIngestReceipt, texts: Map<string,string>): string {
  const refs = (ids: string[]) => ids.map(id => `<a href="#${escape(anchor(id))}">${escape(id)}</a>`).join(' · ');
  const clip = (assetId: string, start: number, end: number) => {
    const a=p.assets.find(a=>a.id===assetId)!;
    return `<video controls preload="metadata" src="${localUri(a.uri)}#t=${start/1000},${end/1000}" aria-label="源素材 ${escape(assetId)}，${start} 至 ${end} 毫秒"></video><p><a href="${localUri(a.uri)}#t=${start/1000},${end/1000}">打开片段 ${start}–${end} ms</a></p>`;
  };
  const cards = (items: {id:string;evidence_ids:string[];description?:string;text?:string;action?:string}[]) => items.map(x=>`<article><h3>${escape(x.id)}</h3><p>${escape(x.description ?? x.text ?? x.action ?? '')}</p><p>证据 ${refs(x.evidence_ids)}</p>${x.evidence_ids.some(id=>p.evidence.find(e=>e.id===id)?.epistemic_status!=='observed')?'<strong class="uncertain">包含推断或重建，待确认</strong>':''}</article>`).join('') || '<p>未提供</p>';
  const evidence = p.evidence.map(e=>{
    const a=p.assets.find(a=>a.id===e.source_asset_id)!;
    let location='';
    if(e.locator.kind==='text') location=`<p>原文 UTF-16 [${e.locator.start_char}, ${e.locator.end_char_exclusive})</p><blockquote>${escape(texts.get(a.id)!.slice(e.locator.start_char,e.locator.end_char_exclusive))}</blockquote>`;
    else if(e.locator.kind==='time') location=clip(a.id,e.locator.start_ms,e.locator.end_ms);
    else location=`<p>帧区间 [${e.locator.start_frame}, ${e.locator.end_frame_exclusive})。变帧率不能按平均帧率换算精确时间；请在本地编辑器核对。</p><a href="${localUri(a.uri)}">打开源文件</a>`;
    return `<article id="${escape(anchor(e.id))}" data-epistemic-status="${e.epistemic_status}"><h3>${escape(e.id)} · ${status[e.epistemic_status]}</h3><p>${escape(e.statement)}</p><p>素材 ${escape(a.id)} · ${e.evidence} · 方法 ${e.method}</p>${location}<ul>${e.uncertainties.map(u=>`<li>${escape(u)}</li>`).join('')}</ul></article>`;
  }).join('');
  const shots=p.storyboard.shots.map(s=>`<article><h3>${escape(s.id)} · ${s.source_in_ms}–${s.source_out_ms} ms</h3><p>${escape(s.action)}</p>${clip(s.source_asset_id,s.source_in_ms,s.source_out_ms)}<p>人物 ${escape(s.character_ids.join('、'))} · 场景 ${escape(s.scene_id)} · 对白 ${escape(s.dialogue_ids.join('、')||'未标注')} · 道具 ${escape(s.prop_ids.join('、')||'无')}</p><p>证据 ${refs(s.evidence_ids)}</p></article>`).join('');
  const subtitles=receipt.assets.filter(a=>a.subtitles).map(a=>`<article><h3>${escape(a.id)}</h3><p>绑定视频 ${escape(a.subtitles!.video_asset_id)}；说话人未识别，字幕不自动变成已确认对白。${a.subtitles!.overlaps.length?`有 ${a.subtitles!.overlaps.length} 组时间重叠，需审阅。`:''}</p><table><tr><th>编号 / 时间</th><th>原文 / UTF-16位置</th><th>说话人</th></tr>${a.subtitles!.cues.map(c=>`<tr><td>${c.index}<br>${c.start_ms}–${c.end_ms} ms</td><td><pre>${escape(c.text)}</pre>[${c.start_char}, ${c.end_char_exclusive})</td><td>未知 / 未绑定</td></tr>`).join('')}</table></article>`).join('')||'<p>未提供SRT</p>';
  return `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; media-src 'self' file:; base-uri 'none'; form-action 'none'"><title>DramaPilot · 源资产审阅</title><style>body{font:16px/1.65 system-ui,sans-serif;margin:0;background:#f5f4ee;color:#193235}main{max-width:1020px;margin:auto;padding:32px 24px}h1{font-size:32px}h2{margin-top:36px}h3{font-size:18px}article{background:white;border:1px solid #dce2df;border-radius:12px;padding:20px;margin:14px 0;overflow-wrap:anywhere}.banner{background:#fff0b6;padding:18px;border-radius:10px}.uncertain{color:#934211}video{width:100%;max-width:560px;display:block;background:#111;border-radius:8px}a{color:#09696c}pre,blockquote{white-space:pre-wrap;overflow-wrap:anywhere}blockquote{margin:12px 0;padding:12px;border-left:3px solid #5b9290;background:#eef5f3}table{border-collapse:collapse;width:100%;font-size:14px}td,th{padding:10px;text-align:left;border-bottom:1px solid #dce2df}code{overflow-wrap:anywhere}nav{display:flex;gap:16px;flex-wrap:wrap}@media(max-width:600px){main{padding:16px}article{padding:14px}table{display:block;overflow:auto}}</style></head><body><main><h1>DramaPilot · 源资产审阅</h1><p class="banner">人工辅助导入 · ${p.assets.some(a=>a.evidence==='fixture')?'含 FIXTURE ONLY 测试素材 · ':''}自动识片未运行 · 内容质量未验证 · 未生成目标短剧</p><p>包 ${escape(p.id)} / revision ${p.revision} · ${escape(p.source_locale)}</p><nav><a href="#shots">源镜头</a><a href="#evidence">证据</a><a href="#entities">人物与场景</a><a href="#subtitles">字幕</a><a href="#unknowns">待确认项</a></nav><h2 id="shots">源镜头与定位</h2>${shots}<h2 id="evidence">证据与不确定性</h2>${evidence}<h2 id="entities">人工提供的人物、关系与场景</h2>${cards(p.characters)}${cards(p.relations)}${cards(p.scenes)}${cards(p.props)}<h2>人工标注的源对白</h2>${p.dialogue.map(d=>`<article><h3>${escape(d.speaker_character_id)} · ${escape(d.id)}</h3><p>${escape(d.text)}</p><p>证据 ${refs(d.evidence_ids)}</p></article>`).join('')||'<p>未提供说话人绑定，不从字幕猜测。</p>'}<h2>故事节拍</h2>${cards(p.beats)}<h2 id="subtitles">原始SRT字幕</h2>${subtitles}<h2 id="unknowns">待确认项与导入边界</h2><ul>${[...p.unknowns,...receipt.warnings].map(u=>`<li>${escape(u)}</li>`).join('')}</ul><p>人工准备：${receipt.preparation.declared_minutes===null?'未声明':`${receipt.preparation.declared_minutes} 分钟（声明值）`}。${escape(receipt.preparation.notes)}</p><p>程序导入耗时 ${receipt.elapsed_ms} ms。文件校验不代表人物、剧情、字幕或素材许可已通过。</p><details><summary>文件与快照记录</summary><p>源包内容hash <code>${receipt.source_package_sha256}</code></p>${receipt.assets.map(a=>`<p>${escape(a.id)} · ${a.bytes} bytes · <code>${a.sha256}</code>${a.probe?` · 视频 ${a.probe.duration_ms} ms / ${a.probe.frame_count??'未知'} 帧`:''}</p>`).join('')}</details></main></body></html>`;
}
